dist: xenial
language: scala
scala:
  - 2.13.1
jdk:
  - openjdk11

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  sbt clean coverage test coverageReport
after_success:
  - sbt coverageAggregate coveralls